In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df=pd.read_csv('../data/raw/zomato.csv')

In [6]:
df.head(11)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
6,https://www.zomato.com/bangalore/rosewood-inte...,"19/1, New Timberyard Layout, Beside Satellite ...",Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,+91 9731716688\r\n080 26740366,Mysore Road,Casual Dining,NaN,"North Indian, South Indian, Andhra, Chinese",800,"[('Rated 5.0', 'RATED\n Awesome food ??Great ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
8,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
9,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari
10,https://www.zomato.com/bangalore/caf%C3%A9-dow...,"12,29 Near PES University Back Gate, D'Souza N...",CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...,Yes,No,4.1/5,402,080 26724489\r\n+91 7406048982,Banashankari,Cafe,"Waffles, Pasta, Crispy Chicken, Honey Chilli C...",Cafe,500,"[('Rated 4.0', 'RATED\n We ended up here on a...",[],Cafes,Banashankari

In [7]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [8]:
df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [9]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [10]:
df.shape

(51717, 17)

In [11]:
df = df[df['url'].str.startswith('http', na=False)]

In [12]:
df.shape

(51717, 17)

In [13]:
df = df[[
    'name',
    'online_order',
    'book_table',
    'rate',
    'votes',
    'location',
    'rest_type',
    'cuisines',
    'approx_cost(for two people)',
    'listed_in(type)',
    'listed_in(city)'
]]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51717 non-null  object
 1   online_order                 51717 non-null  object
 2   book_table                   51717 non-null  object
 3   rate                         43942 non-null  object
 4   votes                        51717 non-null  int64
 5   location                     51696 non-null  object
 6   rest_type                    51490 non-null  object
 7   cuisines                     51672 non-null  object
 8   approx_cost(for two people)  51371 non-null  object
 9   listed_in(type)              51717 non-null  object
 10  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(10)
memory usage: 4.3+ MB

In [15]:
df.isnull().sum()

name                              0
online_order                      0
book_table                        0
rate                           7775
votes                             0
location                         21
rest_type                       227
cuisines                         45
approx_cost(for two people)     346
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

In [16]:
df['rest_type'] = df['rest_type'].fillna('unknown')

In [17]:
df = df.dropna(subset=[
    'name',
    'location',
    'cuisines',
    'rate',
    'approx_cost(for two people)'
])

In [18]:
df.isnull().sum()

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [19]:
df.shape

(43682, 11)

In [22]:
df = df[df['rate'].notnull()]
df = df[~df['rate'].isin(['NEW', '-'])]

df['rate'] = df['rate'].str.replace('/5', '', regex=False)
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

df = df[df['rate'].notnull()]

In [23]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"North Indian, Rajasthani",600,Buffet,Banashankari

In [24]:
df = df.drop_duplicates(subset=['name', 'location'])

In [25]:
df.shape

(9216, 11)

In [26]:
df['location'] = df['location'].str.lower().str.strip()
df['cuisines'] = df['cuisines'].str.lower().str.strip()
df['rest_type'] = df['rest_type'].str.lower().str.strip()

In [27]:
df.head()

,name,online_order,book_table,rate,votes,location,rest_type,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1,775,banashankari,casual dining,"north indian, mughlai, chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,banashankari,casual dining,"chinese, north indian, thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,banashankari,"cafe, casual dining","cafe, mexican, italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,banashankari,quick bites,"south indian, north indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,basavanagudi,casual dining,"north indian, rajasthani",600,Buffet,Banashankari

In [28]:
df = df.rename(columns={
    'rate': 'rating',
    'approx_cost(for two people)': 'cost',
    'listed_in(type)': 'service_type',
    'listed_in(city)': 'city'
})

In [29]:
df.head()

,name,online_order,book_table,rating,votes,location,rest_type,cuisines,cost,service_type,city
0,Jalsa,Yes,Yes,4.1,775,banashankari,casual dining,"north indian, mughlai, chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,banashankari,casual dining,"chinese, north indian, thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,banashankari,"cafe, casual dining","cafe, mexican, italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7,88,banashankari,quick bites,"south indian, north indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8,166,basavanagudi,casual dining,"north indian, rajasthani",600,Buffet,Banashankari

In [30]:
df.reset_index(drop=True, inplace=True)
df['restaurant_id'] = ['R' + str(i) for i in range(1, len(df) + 1)]

In [31]:
df.head()

,name,online_order,book_table,rating,votes,location,rest_type,cuisines,cost,service_type,city,restaurant_id
0,Jalsa,Yes,Yes,4.1,775,banashankari,casual dining,"north indian, mughlai, chinese",800,Buffet,Banashankari,R1
1,Spice Elephant,Yes,No,4.1,787,banashankari,casual dining,"chinese, north indian, thai",800,Buffet,Banashankari,R2
2,San Churro Cafe,Yes,No,3.8,918,banashankari,"cafe, casual dining","cafe, mexican, italian",800,Buffet,Banashankari,R3
3,Addhuri Udupi Bhojana,No,No,3.7,88,banashankari,quick bites,"south indian, north indian",300,Buffet,Banashankari,R4
4,Grand Village,No,No,3.8,166,basavanagudi,casual dining,"north indian, rajasthani",600,Buffet,Banashankari,R5

In [32]:
df = df[[
    'restaurant_id',
    'name',
    'location',
    'rest_type',
    'cuisines',
    'rating',
    'votes',
    'cost',
    'online_order',
    'book_table',
    'service_type',
    'city'
]]

In [33]:
df.head()

,restaurant_id,name,location,rest_type,cuisines,rating,votes,cost,online_order,book_table,service_type,city
0,R1,Jalsa,banashankari,casual dining,"north indian, mughlai, chinese",4.1,775,800,Yes,Yes,Buffet,Banashankari
1,R2,Spice Elephant,banashankari,casual dining,"chinese, north indian, thai",4.1,787,800,Yes,No,Buffet,Banashankari
2,R3,San Churro Cafe,banashankari,"cafe, casual dining","cafe, mexican, italian",3.8,918,800,Yes,No,Buffet,Banashankari
3,R4,Addhuri Udupi Bhojana,banashankari,quick bites,"south indian, north indian",3.7,88,300,No,No,Buffet,Banashankari
4,R5,Grand Village,basavanagudi,casual dining,"north indian, rajasthani",3.8,166,600,No,No,Buffet,Banashankari

In [34]:
df.describe()

            rating         votes
count  9216.000000   9216.000000
mean      3.627246    240.662977
std       0.429277    676.170793
min       1.800000      0.000000
25%       3.300000     16.000000
50%       3.700000     52.000000
75%       3.900000    188.000000
max       4.900000  16345.000000

In [35]:
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0})
df['book_table'] = df['book_table'].map({'Yes': 1, 'No': 0})

In [36]:
df['cost'].dtype

dtype('O')

In [37]:
df['cost'] = df['cost'].astype(str)

# remove commas if any
df['cost'] = df['cost'].str.replace(',', '')

# convert to numeric
df['cost'] = pd.to_numeric(df['cost'], errors='coerce')

In [38]:
df.describe()

            rating         votes         cost  online_order   book_table
count  9216.000000   9216.000000  9216.000000   9216.000000  9216.000000
mean      3.627246    240.662977   536.993164      0.614800     0.100694
std       0.429277    676.170793   427.459232      0.486669     0.300940
min       1.800000      0.000000    40.000000      0.000000     0.000000
25%       3.300000     16.000000   300.000000      0.000000     0.000000
50%       3.700000     52.000000   400.000000      1.000000     0.000000
75%       3.900000    188.000000   600.000000      1.000000     0.000000
max       4.900000  16345.000000  6000.000000      1.000000     1.000000

In [39]:
df.head()

,restaurant_id,name,location,rest_type,cuisines,rating,votes,cost,online_order,book_table,service_type,city
0,R1,Jalsa,banashankari,casual dining,"north indian, mughlai, chinese",4.1,775,800,1,1,Buffet,Banashankari
1,R2,Spice Elephant,banashankari,casual dining,"chinese, north indian, thai",4.1,787,800,1,0,Buffet,Banashankari
2,R3,San Churro Cafe,banashankari,"cafe, casual dining","cafe, mexican, italian",3.8,918,800,1,0,Buffet,Banashankari
3,R4,Addhuri Udupi Bhojana,banashankari,quick bites,"south indian, north indian",3.7,88,300,0,0,Buffet,Banashankari
4,R5,Grand Village,basavanagudi,casual dining,"north indian, rajasthani",3.8,166,600,0,0,Buffet,Banashankari

In [40]:
df['service_type'].value_counts()

service_type
Delivery              6511
Dine-out              1538
Cafes                  487
Desserts               368
Buffet                 289
Pubs and bars           16
Drinks & nightlife       7
Name: count, dtype: int64

In [42]:
df['city'].unique()

array(['Banashankari', 'Bannerghatta Road', 'Basavanagudi', 'Bellandur',
       'Brigade Road', 'Brookefield', 'BTM', 'Church Street',
       'Electronic City', 'Frazer Town', 'HSR', 'Indiranagar',
       'Jayanagar', 'JP Nagar', 'Kalyan Nagar', 'Kammanahalli',
       'Koramangala 4th Block', 'Koramangala 5th Block',
       'Koramangala 6th Block', 'Koramangala 7th Block', 'Lavelle Road',
       'Malleshwaram', 'Marathahalli', 'MG Road', 'New BEL Road',
       'Old Airport Road', 'Rajajinagar', 'Residency Road',
       'Sarjapur Road', 'Whitefield'], dtype=object)

In [47]:
df.tail()

,restaurant_id,name,location,rest_type,cuisines,rating,votes,cost,online_order,book_table,service_type,city
9211,R9212,Chung Wah,"itpl main road, whitefield",casual dining,"chinese, momos",2.5,73,800,0,0,Dine-out,Whitefield
9212,R9213,Nawabs Empire,"itpl main road, whitefield",quick bites,"north indian, chinese, arabian, momos",3.2,5,300,0,0,Dine-out,Whitefield
9213,R9214,Fujian Express,"itpl main road, whitefield",food court,"thai, chinese, momos",3.8,182,600,1,0,Dine-out,Whitefield
9214,R9215,SeeYa Restaurant,kr puram,quick bites,"north indian, kerala, chinese",3.3,4,350,0,0,Dine-out,Whitefield
9215,R9216,Bhagini,whitefield,"casual dining, bar","andhra, south indian, chinese, north indian",2.5,81,800,0,0,Drinks & nightlife,Whitefield

In [48]:
df.to_csv("../data/processed/restaurants_cleaned.csv", index=False)